### ISSUE TITLE
docker-compose up not working as expected

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/test-things#20]
I tried on Windows to run `docker-compose up` as described [here](https://github.com/eclipse-thingweb/test-things?tab=readme-ov-file#how-to-run).

Anyhow, it fails with the following errors.

![image](https://github.com/eclipse-thingweb/test-things/assets/11281461/85aefbe0-1bbb-49be-9212-7f2ff9602e4f)

**Comment by egekorkan** [comment]
Do other docker images run? E.g. `docker run hello-world`

**Comment by danielpeintner** [comment]
> Do other docker images run? E.g. `docker run hello-world`

Yes!

![image](https://github.com/eclipse-thingweb/test-things/assets/11281461/49f60ef2-57cd-4c84-b033-26f06a10deb0)

**Comment by danielpeintner** [comment]
Maybe related to https://github.com/docker/compose/issues/11421
I am on `v4.27.1`

**Comment by danielpeintner** [comment]
downgrading docker desktop to 4.26.1 fixes the issue.
