### ISSUE TITLE
Improve README with information of the things running

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/test-things#21]
The following [section](https://github.com/eclipse-thingweb/test-things#how-to-run) explains how simple it is to run the things with `docker-compose up`. Good so far.

What I am missing is information on where certain things are visible and maybe an overall list.

E.g., http://localhost/ reports a 404 and one has to dig into the code to find for example http://localhost/http-express-calculator.
Maybe the README can contain this information or the log of docker or there could be some information in the root of HTTP etc.
Not sure w.r.t. other protocols.

**Comment by hasanheroglu** [comment]
I'll take care of this.
