### ISSUE TITLE
HTTP Online things should report correct contentType

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/test-things#22]
Running test thing reports JSON TDs like this..

![image](https://github.com/eclipse-thingweb/test-things/assets/11281461/e8b297e6-97be-428d-9d62-f441a92807d6)

Hence, it is not returned as JSON 

____

see  http://plugfest.thingweb.io:8083/counter for example, which indicates it is `application/json`

![image](https://github.com/eclipse-thingweb/test-things/assets/11281461/695e35f4-468c-4156-9f51-5c7f2f91d56f)

**Comment by egekorkan** [comment]
Gonna be fixed by #16
