### ISSUE TITLE
Coap calculator content negotiation's request headers requires a null check  

### ISSUE THREAD

**Issue by hasanheroglu** [eclipse-thingweb/test-things#27]
Request's accept headers can be null in case they are not provided. This causes an error when .includes method called on the undefined variable.  

Error happens here:
https://github.com/eclipse-thingweb/test-things/blob/828ab32091ee92a6298e6d0b274822ab61d3be04/things/calculator/coap/js/coap-content-negotiation-calculator.js#L220

**Comment by egekorkan** [comment]
The issue discovered at #25 can be also addressed within the same scope
