### ISSUE TITLE
node-wot Things

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/test-things#3]
Still in discussion but the idea is to also add node-wot Things and manage them via a single docker compose

**Comment by egekorkan** [comment]
We have taken a decision on today's call. The following Thing's source code should be moved here and integrated into docker-compose configuration:

- 3 Things at https://github.com/eclipse-thingweb/node-wot/tree/master/packages/examples/src/quickstart
- Test Thing: https://github.com/eclipse-thingweb/node-wot/blob/master/packages/examples/src/testthing/testthing.ts . Its client code should be put as a test. The WoT object should be constructed in the same file (not using CLI)
- Smart Coffee Machine: https://github.com/eclipse-thingweb/node-wot/blob/master/packages/examples/src/scripts/smart-coffee-machine.ts . Its client should be put as a test. The WoT object should be constructed in the same file (not using CLI)


Given that clients are going to be used as tests, there can be new errors coming up. So in one commit, the original code can be moved and another commit can do the necessary changes.

**Comment by hasanheroglu** [comment]
I will handle this.

**Comment by egekorkan** [comment]
We have to do some workarounds here since the TD exposed by node-wot will be incorrect. The hostname can be plugfest.thingweb.io since node-wot does not check but the port will be wrong. The ports are changed by Traefik (at least we do so for now) so we have to make sure that people do not get the node-wot exposed TD (e.g. http://plugfest.thingweb.io:8083/testthing should not be retrievable). The correct TD will be in the TDD and the GitHub repo. We can block the node-wot TD with some configs in Traefik.
