### ISSUE TITLE
Thing State Dashboard

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/test-things#33]
For anyone interacting with Things over the specific protocol, it would be good to have knowledge about the Thing's current and past state:

- Property: value, observe subscriptions
- Action: invocation, received input, given output
- Events: emitted value, subscription amount, subscription request payloads and unsubscription request payloads (not sure how they work in general)
- Health Check of the Thing (feature of docker compose/stack)

All these should have historical values.

These can be integrated to Grafana but needs to be public. The dashboard should not be able to send values back to the Things.

**Comment by hasanheroglu** [comment]
I will handle this.
