### ISSUE TITLE
Port Configuration in docker-compose to have less external ports

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/test-things#5]
The current docker-compose file maps one port per Thing but since we want to add many Things here and do not want to ask for many ports from Eclipse, we should map one port to multiple devices internally. We need some routing of course. Some directions forward: 
- https://doc.traefik.io/traefik/providers/docker/
- https://docs.docker.com/network/

**Comment by egekorkan** [comment]
@hasanheroglu will be looking at this

**Comment by hasanheroglu** [comment]
I'll look at this.
