### ISSUE TITLE
Modbus Test Things

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/test-things#7]
We should Modbus Test Things since it is one of the bindings at https://w3c.github.io/wot-binding-templates/bindings/protocols/modbus. However, it cannot be based on the calculator since it is more property-driven. This is gonna be the case for BACnet so we can use the same TM.

Also see https://github.com/yaacov/node-modbus-serial#modbustcp-server

**Comment by egekorkan** [comment]
@hasanheroglu will be looking at this

**Comment by hasanheroglu** [comment]
I'll look at this.
