### ISSUE TITLE
Communication Tests

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/test-things#8]
So far, we only test the TMs and TDs but not the communication. We should have end to end tests where a Consumer sends the requests. Ideally a node-wot consumer to really test TD consuming.

**Comment by egekorkan** [comment]
This is now possible since we have the tests folder in each Thing for coap and HTTP. New ones should be written for mqtt and modbus. Also #3 is bringing test code for the new ones coming in.

**Comment by hasanheroglu** [comment]
I will handle this.
